# blockchain alienchain api info
alienchain:
  api:
    url:
    username:
    password:

spring:
  application:
    name: explorer
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
    druid:
      validationQuery: SELECT 1
      initialSize: 2
      minIdle: 2
      maxActive: 20
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat:
        enabled: true
        merge-sql: false
        slow-sql-millis: 1000
        log-slow-sql: true
        connection-stack-trace-enable: false

      slf4j:
        enabled: true
        data-source-log-enabled: true
        connection-log-enabled: true
        connection-log-error-enabled: true
        statement-log-enabled: false
        statement-executable-sql-log-enable: true
        result-set-log-enabled: false
        statement-sql-format-option:
          upp-case: false
          desensitize: false
          pretty-format: true
          parameterized: false
        statement-sql-pretty-format: true
      wall:
        enabled: true
        log-violation: true
        config:
          delete-where-none-check: true
      config:
        enabled: false

      web-stat:
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        url-patterns: /*

      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid
        url-mappings: /druid/*

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.alienchain.explorer
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-prefix: executableSql.
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: org.alienchain.explorer
  global-config:
    id-type: 0
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
    metaObjectHandler:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    druid.sql: info
    com.ibatis: info
    com.baomidou: info

server:
  tomcat:
    uri-encoding: UTF-8
