/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractExchangeInjectRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractExchangeInject extends TableImpl<ContractExchangeInjectRecord> {

    private static final long serialVersionUID = -689374469;

    /**
     * The reference instance of <code>tmp.contract_exchange_inject</code>
     */
    public static final ContractExchangeInject CONTRACT_EXCHANGE_INJECT = new ContractExchangeInject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractExchangeInjectRecord> getRecordType() {
        return ContractExchangeInjectRecord.class;
    }

    /**
     * The column <code>tmp.contract_exchange_inject.id</code>.
     */
    public final TableField<ContractExchangeInjectRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_exchange_inject.owner_address</code>.
     */
    public final TableField<ContractExchangeInjectRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_exchange_inject.transaction_id</code>.
     */
    public final TableField<ContractExchangeInjectRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_exchange_inject</code> table reference
     */
    public ContractExchangeInject() {
        this("contract_exchange_inject", null);
    }

    /**
     * Create an aliased <code>tmp.contract_exchange_inject</code> table reference
     */
    public ContractExchangeInject(String alias) {
        this(alias, CONTRACT_EXCHANGE_INJECT);
    }

    private ContractExchangeInject(String alias, Table<ContractExchangeInjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractExchangeInject(String alias, Table<ContractExchangeInjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractExchangeInjectRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_EXCHANGE_INJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractExchangeInjectRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_EXCHANGE_INJECT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractExchangeInjectRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractExchangeInjectRecord>>asList(Keys.KEY_CONTRACT_EXCHANGE_INJECT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractExchangeInjectRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractExchangeInjectRecord, ?>>asList(Keys.FK_CONTRACT_EXCHANGE_INJECT_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractExchangeInject as(String alias) {
        return new ContractExchangeInject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractExchangeInject rename(String name) {
        return new ContractExchangeInject(name, null);
    }
}
