/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractBuyStorageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractBuyStorage extends TableImpl<ContractBuyStorageRecord> {

    private static final long serialVersionUID = -762367392;

    /**
     * The reference instance of <code>tmp.contract_buy_storage</code>
     */
    public static final ContractBuyStorage CONTRACT_BUY_STORAGE = new ContractBuyStorage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractBuyStorageRecord> getRecordType() {
        return ContractBuyStorageRecord.class;
    }

    /**
     * The column <code>tmp.contract_buy_storage.id</code>.
     */
    public final TableField<ContractBuyStorageRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_buy_storage.owner_address</code>.
     */
    public final TableField<ContractBuyStorageRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_buy_storage.transaction_id</code>.
     */
    public final TableField<ContractBuyStorageRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_buy_storage</code> table reference
     */
    public ContractBuyStorage() {
        this("contract_buy_storage", null);
    }

    /**
     * Create an aliased <code>tmp.contract_buy_storage</code> table reference
     */
    public ContractBuyStorage(String alias) {
        this(alias, CONTRACT_BUY_STORAGE);
    }

    private ContractBuyStorage(String alias, Table<ContractBuyStorageRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractBuyStorage(String alias, Table<ContractBuyStorageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractBuyStorageRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_BUY_STORAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractBuyStorageRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_BUY_STORAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractBuyStorageRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractBuyStorageRecord>>asList(Keys.KEY_CONTRACT_BUY_STORAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractBuyStorageRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractBuyStorageRecord, ?>>asList(Keys.FK_CONTRACT_BUY_STORAGE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractBuyStorage as(String alias) {
        return new ContractBuyStorage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractBuyStorage rename(String name) {
        return new ContractBuyStorage(name, null);
    }
}
