/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractUpdateAssetRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractUpdateAsset extends TableImpl<ContractUpdateAssetRecord> {

    private static final long serialVersionUID = -558335980;

    /**
     * The reference instance of <code>tmp.contract_update_asset</code>
     */
    public static final ContractUpdateAsset CONTRACT_UPDATE_ASSET = new ContractUpdateAsset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractUpdateAssetRecord> getRecordType() {
        return ContractUpdateAssetRecord.class;
    }

    /**
     * The column <code>tmp.contract_update_asset.id</code>.
     */
    public final TableField<ContractUpdateAssetRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_update_asset.owner_address</code>.
     */
    public final TableField<ContractUpdateAssetRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_update_asset.transaction_id</code>.
     */
    public final TableField<ContractUpdateAssetRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_update_asset</code> table reference
     */
    public ContractUpdateAsset() {
        this("contract_update_asset", null);
    }

    /**
     * Create an aliased <code>tmp.contract_update_asset</code> table reference
     */
    public ContractUpdateAsset(String alias) {
        this(alias, CONTRACT_UPDATE_ASSET);
    }

    private ContractUpdateAsset(String alias, Table<ContractUpdateAssetRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractUpdateAsset(String alias, Table<ContractUpdateAssetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractUpdateAssetRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_UPDATE_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractUpdateAssetRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_UPDATE_ASSET_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractUpdateAssetRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractUpdateAssetRecord>>asList(Keys.KEY_CONTRACT_UPDATE_ASSET_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractUpdateAssetRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractUpdateAssetRecord, ?>>asList(Keys.FK_CONTRACT_UPDATE_ASSET_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractUpdateAsset as(String alias) {
        return new ContractUpdateAsset(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractUpdateAsset rename(String name) {
        return new ContractUpdateAsset(name, null);
    }
}
