/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractExchangeCreateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractExchangeCreate extends TableImpl<ContractExchangeCreateRecord> {

    private static final long serialVersionUID = 558632814;

    /**
     * The reference instance of <code>tmp.contract_exchange_create</code>
     */
    public static final ContractExchangeCreate CONTRACT_EXCHANGE_CREATE = new ContractExchangeCreate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractExchangeCreateRecord> getRecordType() {
        return ContractExchangeCreateRecord.class;
    }

    /**
     * The column <code>tmp.contract_exchange_create.id</code>.
     */
    public final TableField<ContractExchangeCreateRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_exchange_create.owner_address</code>.
     */
    public final TableField<ContractExchangeCreateRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_exchange_create.transaction_id</code>.
     */
    public final TableField<ContractExchangeCreateRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_exchange_create</code> table reference
     */
    public ContractExchangeCreate() {
        this("contract_exchange_create", null);
    }

    /**
     * Create an aliased <code>tmp.contract_exchange_create</code> table reference
     */
    public ContractExchangeCreate(String alias) {
        this(alias, CONTRACT_EXCHANGE_CREATE);
    }

    private ContractExchangeCreate(String alias, Table<ContractExchangeCreateRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractExchangeCreate(String alias, Table<ContractExchangeCreateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractExchangeCreateRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_EXCHANGE_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractExchangeCreateRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_EXCHANGE_CREATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractExchangeCreateRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractExchangeCreateRecord>>asList(Keys.KEY_CONTRACT_EXCHANGE_CREATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractExchangeCreateRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractExchangeCreateRecord, ?>>asList(Keys.FK_CONTRACT_EXCHANGE_CREATE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractExchangeCreate as(String alias) {
        return new ContractExchangeCreate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractExchangeCreate rename(String name) {
        return new ContractExchangeCreate(name, null);
    }
}
