/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractSetAccountIdRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractSetAccountId extends TableImpl<ContractSetAccountIdRecord> {

    private static final long serialVersionUID = 823541018;

    /**
     * The reference instance of <code>tmp.contract_set_account_id</code>
     */
    public static final ContractSetAccountId CONTRACT_SET_ACCOUNT_ID = new ContractSetAccountId();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractSetAccountIdRecord> getRecordType() {
        return ContractSetAccountIdRecord.class;
    }

    /**
     * The column <code>tmp.contract_set_account_id.id</code>.
     */
    public final TableField<ContractSetAccountIdRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_set_account_id.owner_address</code>.
     */
    public final TableField<ContractSetAccountIdRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_set_account_id.transaction_id</code>.
     */
    public final TableField<ContractSetAccountIdRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_set_account_id</code> table reference
     */
    public ContractSetAccountId() {
        this("contract_set_account_id", null);
    }

    /**
     * Create an aliased <code>tmp.contract_set_account_id</code> table reference
     */
    public ContractSetAccountId(String alias) {
        this(alias, CONTRACT_SET_ACCOUNT_ID);
    }

    private ContractSetAccountId(String alias, Table<ContractSetAccountIdRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractSetAccountId(String alias, Table<ContractSetAccountIdRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractSetAccountIdRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_SET_ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractSetAccountIdRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_SET_ACCOUNT_ID_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractSetAccountIdRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractSetAccountIdRecord>>asList(Keys.KEY_CONTRACT_SET_ACCOUNT_ID_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractSetAccountIdRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractSetAccountIdRecord, ?>>asList(Keys.FK_CONTRACT_SET_ACCOUNT_ID_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractSetAccountId as(String alias) {
        return new ContractSetAccountId(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractSetAccountId rename(String name) {
        return new ContractSetAccountId(name, null);
    }
}
