/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractCreateSmartcontractRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractCreateSmartcontract extends TableImpl<ContractCreateSmartcontractRecord> {

    private static final long serialVersionUID = 1902192046;

    /**
     * The reference instance of <code>tmp.contract_create_smartcontract</code>
     */
    public static final ContractCreateSmartcontract CONTRACT_CREATE_SMARTCONTRACT = new ContractCreateSmartcontract();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractCreateSmartcontractRecord> getRecordType() {
        return ContractCreateSmartcontractRecord.class;
    }

    /**
     * The column <code>tmp.contract_create_smartcontract.id</code>.
     */
    public final TableField<ContractCreateSmartcontractRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_create_smartcontract.owner_address</code>.
     */
    public final TableField<ContractCreateSmartcontractRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_create_smartcontract.transaction_id</code>.
     */
    public final TableField<ContractCreateSmartcontractRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_create_smartcontract</code> table reference
     */
    public ContractCreateSmartcontract() {
        this("contract_create_smartcontract", null);
    }

    /**
     * Create an aliased <code>tmp.contract_create_smartcontract</code> table reference
     */
    public ContractCreateSmartcontract(String alias) {
        this(alias, CONTRACT_CREATE_SMARTCONTRACT);
    }

    private ContractCreateSmartcontract(String alias, Table<ContractCreateSmartcontractRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractCreateSmartcontract(String alias, Table<ContractCreateSmartcontractRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractCreateSmartcontractRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_CREATE_SMARTCONTRACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractCreateSmartcontractRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_CREATE_SMARTCONTRACT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractCreateSmartcontractRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractCreateSmartcontractRecord>>asList(Keys.KEY_CONTRACT_CREATE_SMARTCONTRACT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractCreateSmartcontractRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractCreateSmartcontractRecord, ?>>asList(Keys.FK_CONTRACT_CREATE_SMARTCONTRACT_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractCreateSmartcontract as(String alias) {
        return new ContractCreateSmartcontract(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractCreateSmartcontract rename(String name) {
        return new ContractCreateSmartcontract(name, null);
    }
}
