/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractBuyStorageBytesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractBuyStorageBytes extends TableImpl<ContractBuyStorageBytesRecord> {

    private static final long serialVersionUID = 54550768;

    /**
     * The reference instance of <code>tmp.contract_buy_storage_bytes</code>
     */
    public static final ContractBuyStorageBytes CONTRACT_BUY_STORAGE_BYTES = new ContractBuyStorageBytes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractBuyStorageBytesRecord> getRecordType() {
        return ContractBuyStorageBytesRecord.class;
    }

    /**
     * The column <code>tmp.contract_buy_storage_bytes.id</code>.
     */
    public final TableField<ContractBuyStorageBytesRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_buy_storage_bytes.owner_address</code>.
     */
    public final TableField<ContractBuyStorageBytesRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_buy_storage_bytes.transaction_id</code>.
     */
    public final TableField<ContractBuyStorageBytesRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_buy_storage_bytes</code> table reference
     */
    public ContractBuyStorageBytes() {
        this("contract_buy_storage_bytes", null);
    }

    /**
     * Create an aliased <code>tmp.contract_buy_storage_bytes</code> table reference
     */
    public ContractBuyStorageBytes(String alias) {
        this(alias, CONTRACT_BUY_STORAGE_BYTES);
    }

    private ContractBuyStorageBytes(String alias, Table<ContractBuyStorageBytesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractBuyStorageBytes(String alias, Table<ContractBuyStorageBytesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractBuyStorageBytesRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_BUY_STORAGE_BYTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractBuyStorageBytesRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_BUY_STORAGE_BYTES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractBuyStorageBytesRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractBuyStorageBytesRecord>>asList(Keys.KEY_CONTRACT_BUY_STORAGE_BYTES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractBuyStorageBytesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractBuyStorageBytesRecord, ?>>asList(Keys.FK_CONTRACT_BUY_STORAGE_BYTES_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractBuyStorageBytes as(String alias) {
        return new ContractBuyStorageBytes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractBuyStorageBytes rename(String name) {
        return new ContractBuyStorageBytes(name, null);
    }
}
