/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractExchangeTransactionContractRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractExchangeTransactionContract extends TableImpl<ContractExchangeTransactionContractRecord> {

    private static final long serialVersionUID = 1944489139;

    /**
     * The reference instance of <code>tmp.contract_exchange_transaction_contract</code>
     */
    public static final ContractExchangeTransactionContract CONTRACT_EXCHANGE_TRANSACTION_CONTRACT = new ContractExchangeTransactionContract();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractExchangeTransactionContractRecord> getRecordType() {
        return ContractExchangeTransactionContractRecord.class;
    }

    /**
     * The column <code>tmp.contract_exchange_transaction_contract.id</code>.
     */
    public final TableField<ContractExchangeTransactionContractRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_exchange_transaction_contract.owner_address</code>.
     */
    public final TableField<ContractExchangeTransactionContractRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_exchange_transaction_contract.transaction_id</code>.
     */
    public final TableField<ContractExchangeTransactionContractRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_exchange_transaction_contract</code> table reference
     */
    public ContractExchangeTransactionContract() {
        this("contract_exchange_transaction_contract", null);
    }

    /**
     * Create an aliased <code>tmp.contract_exchange_transaction_contract</code> table reference
     */
    public ContractExchangeTransactionContract(String alias) {
        this(alias, CONTRACT_EXCHANGE_TRANSACTION_CONTRACT);
    }

    private ContractExchangeTransactionContract(String alias, Table<ContractExchangeTransactionContractRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractExchangeTransactionContract(String alias, Table<ContractExchangeTransactionContractRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractExchangeTransactionContractRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_EXCHANGE_TRANSACTION_CONTRACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractExchangeTransactionContractRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_EXCHANGE_TRANSACTION_CONTRACT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractExchangeTransactionContractRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractExchangeTransactionContractRecord>>asList(Keys.KEY_CONTRACT_EXCHANGE_TRANSACTION_CONTRACT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractExchangeTransactionContractRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractExchangeTransactionContractRecord, ?>>asList(Keys.FK_CONTRACT_EXCHANGE_TRANSACTION_CONTRACT_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractExchangeTransactionContract as(String alias) {
        return new ContractExchangeTransactionContract(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractExchangeTransactionContract rename(String name) {
        return new ContractExchangeTransactionContract(name, null);
    }
}
