/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractProposalApproveRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractProposalApprove extends TableImpl<ContractProposalApproveRecord> {

    private static final long serialVersionUID = 1755692422;

    /**
     * The reference instance of <code>tmp.contract_proposal_approve</code>
     */
    public static final ContractProposalApprove CONTRACT_PROPOSAL_APPROVE = new ContractProposalApprove();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractProposalApproveRecord> getRecordType() {
        return ContractProposalApproveRecord.class;
    }

    /**
     * The column <code>tmp.contract_proposal_approve.id</code>.
     */
    public final TableField<ContractProposalApproveRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_proposal_approve.owner_address</code>.
     */
    public final TableField<ContractProposalApproveRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_proposal_approve.transaction_id</code>.
     */
    public final TableField<ContractProposalApproveRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_proposal_approve</code> table reference
     */
    public ContractProposalApprove() {
        this("contract_proposal_approve", null);
    }

    /**
     * Create an aliased <code>tmp.contract_proposal_approve</code> table reference
     */
    public ContractProposalApprove(String alias) {
        this(alias, CONTRACT_PROPOSAL_APPROVE);
    }

    private ContractProposalApprove(String alias, Table<ContractProposalApproveRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractProposalApprove(String alias, Table<ContractProposalApproveRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractProposalApproveRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_PROPOSAL_APPROVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractProposalApproveRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_PROPOSAL_APPROVE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractProposalApproveRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractProposalApproveRecord>>asList(Keys.KEY_CONTRACT_PROPOSAL_APPROVE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractProposalApproveRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractProposalApproveRecord, ?>>asList(Keys.FK_CONTRACT_PROPOSAL_APPROVE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractProposalApprove as(String alias) {
        return new ContractProposalApprove(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractProposalApprove rename(String name) {
        return new ContractProposalApprove(name, null);
    }
}
