/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractProposalDeleteRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractProposalDelete extends TableImpl<ContractProposalDeleteRecord> {

    private static final long serialVersionUID = -879370646;

    /**
     * The reference instance of <code>tmp.contract_proposal_delete</code>
     */
    public static final ContractProposalDelete CONTRACT_PROPOSAL_DELETE = new ContractProposalDelete();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractProposalDeleteRecord> getRecordType() {
        return ContractProposalDeleteRecord.class;
    }

    /**
     * The column <code>tmp.contract_proposal_delete.id</code>.
     */
    public final TableField<ContractProposalDeleteRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_proposal_delete.owner_address</code>.
     */
    public final TableField<ContractProposalDeleteRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_proposal_delete.transaction_id</code>.
     */
    public final TableField<ContractProposalDeleteRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_proposal_delete</code> table reference
     */
    public ContractProposalDelete() {
        this("contract_proposal_delete", null);
    }

    /**
     * Create an aliased <code>tmp.contract_proposal_delete</code> table reference
     */
    public ContractProposalDelete(String alias) {
        this(alias, CONTRACT_PROPOSAL_DELETE);
    }

    private ContractProposalDelete(String alias, Table<ContractProposalDeleteRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractProposalDelete(String alias, Table<ContractProposalDeleteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractProposalDeleteRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_PROPOSAL_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractProposalDeleteRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_PROPOSAL_DELETE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractProposalDeleteRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractProposalDeleteRecord>>asList(Keys.KEY_CONTRACT_PROPOSAL_DELETE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractProposalDeleteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractProposalDeleteRecord, ?>>asList(Keys.FK_CONTRACT_PROPOSAL_DELETE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractProposalDelete as(String alias) {
        return new ContractProposalDelete(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractProposalDelete rename(String name) {
        return new ContractProposalDelete(name, null);
    }
}
