/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractUpdateSettingRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractUpdateSetting extends TableImpl<ContractUpdateSettingRecord> {

    private static final long serialVersionUID = -1073028044;

    /**
     * The reference instance of <code>tmp.contract_update_setting</code>
     */
    public static final ContractUpdateSetting CONTRACT_UPDATE_SETTING = new ContractUpdateSetting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractUpdateSettingRecord> getRecordType() {
        return ContractUpdateSettingRecord.class;
    }

    /**
     * The column <code>tmp.contract_update_setting.id</code>.
     */
    public final TableField<ContractUpdateSettingRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_update_setting.owner_address</code>.
     */
    public final TableField<ContractUpdateSettingRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_update_setting.transaction_id</code>.
     */
    public final TableField<ContractUpdateSettingRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_update_setting</code> table reference
     */
    public ContractUpdateSetting() {
        this("contract_update_setting", null);
    }

    /**
     * Create an aliased <code>tmp.contract_update_setting</code> table reference
     */
    public ContractUpdateSetting(String alias) {
        this(alias, CONTRACT_UPDATE_SETTING);
    }

    private ContractUpdateSetting(String alias, Table<ContractUpdateSettingRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractUpdateSetting(String alias, Table<ContractUpdateSettingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractUpdateSettingRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_UPDATE_SETTING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractUpdateSettingRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_UPDATE_SETTING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractUpdateSettingRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractUpdateSettingRecord>>asList(Keys.KEY_CONTRACT_UPDATE_SETTING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractUpdateSettingRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractUpdateSettingRecord, ?>>asList(Keys.FK_CONTRACT_UPDATE_SETTING_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractUpdateSetting as(String alias) {
        return new ContractUpdateSetting(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractUpdateSetting rename(String name) {
        return new ContractUpdateSetting(name, null);
    }
}
