/*
 * This file is generated by jOOQ.
*/
package org.alienchain.explorer.model.tables;


import org.alienchain.explorer.model.Keys;
import org.alienchain.explorer.model.Tmp;
import org.alienchain.explorer.model.tables.records.ContractSellStorageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractSellStorage extends TableImpl<ContractSellStorageRecord> {

    private static final long serialVersionUID = -2130678496;

    /**
     * The reference instance of <code>tmp.contract_sell_storage</code>
     */
    public static final ContractSellStorage CONTRACT_SELL_STORAGE = new ContractSellStorage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractSellStorageRecord> getRecordType() {
        return ContractSellStorageRecord.class;
    }

    /**
     * The column <code>tmp.contract_sell_storage.id</code>.
     */
    public final TableField<ContractSellStorageRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tmp.contract_sell_storage.owner_address</code>.
     */
    public final TableField<ContractSellStorageRecord, String> OWNER_ADDRESS = createField("owner_address", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>tmp.contract_sell_storage.transaction_id</code>.
     */
    public final TableField<ContractSellStorageRecord, ULong> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>tmp.contract_sell_storage</code> table reference
     */
    public ContractSellStorage() {
        this("contract_sell_storage", null);
    }

    /**
     * Create an aliased <code>tmp.contract_sell_storage</code> table reference
     */
    public ContractSellStorage(String alias) {
        this(alias, CONTRACT_SELL_STORAGE);
    }

    private ContractSellStorage(String alias, Table<ContractSellStorageRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractSellStorage(String alias, Table<ContractSellStorageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tmp.TMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContractSellStorageRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CONTRACT_SELL_STORAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContractSellStorageRecord> getPrimaryKey() {
        return Keys.KEY_CONTRACT_SELL_STORAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContractSellStorageRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractSellStorageRecord>>asList(Keys.KEY_CONTRACT_SELL_STORAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContractSellStorageRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractSellStorageRecord, ?>>asList(Keys.FK_CONTRACT_SELL_STORAGE_TX_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractSellStorage as(String alias) {
        return new ContractSellStorage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractSellStorage rename(String name) {
        return new ContractSellStorage(name, null);
    }
}
